dist: xenial  # Ubuntu 16.04 (required for python 3.7)
language: python
python: 3.7
branches:
  only:
  - gh-pages
  - /.*/
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  #- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  #- echo "deb https://cran.rstudio.com/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
  #- echo "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | sudo tee -a /etc/apt/sources.list
  - echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran40/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  #- conda install -c conda-forge r-base=4.2.2
  - sudo apt-get --allow-unauthenticated install -y r-base
  #- sudo apt-get -f install
  #- sudo apt --fix-broken install
  #- sudo Rscript -e "install.packages('knitr', repos = 'https://', dependencies = TRUE)"
  #- sudo Rscript -e "install.packages('stringr', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  #- sudo Rscript -e "install.packages('checkpoint', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  #- sudo Rscript -e "install.packages('ggplot2', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  - sudo Rscript -e "install.packages('knitr', repos = 'https://', dependencies = TRUE)"
  - sudo Rscript -e "install.packages('stringr', repos = 'https://cloud.r-project.org', dependencies = TRUE)"
  - sudo Rscript -e "install.packages('checkpoint', repos = 'https://cloud.r-project.org', dependencies = TRUE)"
  - sudo Rscript -e "install.packages('ggplot2', repos = 'https://cloud.r-project.org', dependencies = TRUE)"
  - rvm default
  - gem update --system
  #- gem install public_suffix -v 4.0.7
  #- gem install rouge -v 3.30.0
  - gem install json kramdown jekyll
install:
  - pip install pyyaml
script:
  - make lesson-check-all
  - make --always-make site
